baseurl: /
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
languageCode: en-US
paginate: 7
rssLimit: 10
outputs:
  home:
    - HTML
    - RSS
    - REDIRECTS
    - HEADERS
  section:
    - HTML
    - RSS
    - SITEMAP
mediaTypes:
  text/netlify:
    suffixes:
      - ''
    delimiter: ''
outputFormats:
  REDIRECTS:
    mediaType: text/netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  HEADERS:
    mediaType: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true
  SITEMAP:
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap
markup:
  goldmark:
    extensions:
      linkify: false
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: dracula
    tabWidth: 4
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
taxonomies:
  contributor: contributors
permalinks:
  blog: '/blog/:title/'
module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
    - source: node_modules/lazysizes
      target: assets/js/vendor/lazysizes
    - source: node_modules/instant.page
      target: assets/js/vendor/instant.page
    - source: node_modules/lazysizes
      target: assets/js/vendor/lazysizes
    - source: node_modules/flexsearch
      target: assets/js/vendor/flexsearch
    - source: node_modules/clipboard
      target: assets/js/vendor/clipboard
