title: Salim KAYABASI
homepageName: SK
titleSeparator: '-'
titleAddition: yet another personal blog!
description: >-
  Empowering team members to archive collaborative goals. Always aiming for team success.
  Experienced on engineering and a great team player with a demonstrated history of working in the transportation/ride hailing/car-sharing industry.
images:
  - doks.png
twitterSite: salimkayabasi
twitterCreator: salimkayabasi
ogLocale: en_US
schemaType: Person
schemaLogo: favicons/favicon-512x512.png
schemaTwitter: https://twitter.com/salimkayabasi
schemaLinkedIn: https://www.linkedin.com/in/salimkayabasi
schemaGitHub: https://github.com/salimkayabasi
schemaSection: blog
siteLinksSearchBox: true
themeColor: '#fff'
quality: 85
bgColor: '#fff'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
footer: >-
  Any questions or feedback,</br>
  please feel free to share them with me</br>
  <a target="_blank" href="https://twitter.com/salimkayabasi">@salimkayabasi</a>
alert: false
alertText: >-
  Wanna share your feedback? <a class="alert-link"
  target="_blank" href="https://twitter.com/salimkayabasi">@salimkayabasi</a>
docsRepo: https://github.com/salimkayabasi.com
editPage: false
options:
  lazySizes: true
  clipBoard: true
  instantPage: true
  flexSearch: true
  darkMode: true
  bootStrapJs: false
  breadCrumb: true
  highLight: true

