title: SK
titleSeparator: '-'
titleAddition: Welcome to SK's personal webpage
description: >-
  Empowering team members to archive collaborative goals. Always aiming for team success.
  Experienced on engineering and a great team player with a demonstrated history of working in the transportation/ride hailing/car-sharing industry.
images:
  - doks.png
twitterSite: salimkayabasi
twitterCreator: salimkayabasi
ogLocale: en_US
schemaType: Person
schemaLogo: logo-doks.png
schemaTwitter: https://twitter.com/salimkayabasi
schemaLinkedIn: https://www.linkedin.com/in/salimkayabasi
schemaGitHub: https://github.com/salimkayabasi
schemaSection: blog
siteLinksSearchBox: false
themeColor: '#fff'
quality: 85
bgColor: '#fff'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
footer: >-
  Any questions or feedback,</br>
  please feel free to share them with me</br>
  <a href="https://twitter.com/salimkayabasi">@salimkayabasi</a>
alert: false
alertText: >-
  Wanna share your feedback? <a class="alert-link"
  href="https://twitter.com/salimkayabasi">@salimkayabasi</a>.
  Thanks!</a>
docsRepo: https://github.com/salimkayabasi.com
editPage: false
