extends: "airbnb"

parser: "babel-eslint"

env:
  browser: true
  node: true
  es6: true
  jest: true

parserOptions:
 ecmaVersion: 6
 sourceType: "module"
 ecmaFeatures:
   classes: true,
   jsx: true

plugins:
  - import
  - react
  - jsx-a11y
  - prettier

rules:
  no-console: error
  prettier/prettier:
  - warn
  - trailingComma: all
    singleQuote: true
