language: node_js
node_js:
  - "node"
  - "6.10"
cache:
  yarn: true
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
