json: true
clean: true
folder: build
file: me.json

tokens:
  github: ${GH_TOKEN}

template:
  options:
  file: '../salimkayabasi.com/template.html'
  sources:
    profile:
      type: 'data'
      data:
        name: Salim KAYABASI
        photo: https://lh3.googleusercontent.com/B2G2t605HLpRlS6dEgW96LwekkQaNXvq9sRuBBijqq4tdQ0k09bnWKS0Bq8CNyqwuMYbm2uwbEaB62E=w5760-h3600-rw-no
        title: Software Engineer
        location: in Berlin, Germany
        describe: life is almost perfect
    github1:
      type: github
      options:
        user: salimkayabasi
    twitter:
      type: twitter-timeline
      options:
        username: salimkayabasi
        height: 280
        width: 235
