baseURL = "http://blog.salimkayabasi.com/"
languageCode = "en-us"
title = "Salim KAYABASI"
theme="meduimish"
summaryLength = 25
[params.author]
    name = "Salim KAYABASI"
    thumbnail = "/images/salim.png"
    description = "Love to share"
[params.social]
    github = "salimkayabasi"
    linkedin = "salimkayabasi"
    twitter = "salimkayabasi"
[params.index]
    picture = "/images/salim.png"
    title = "Salim KAYABASI"
    subtitle = "I'm a unique placeholder. Working here and there!"
    mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!\
    **This textblock is a demonstration of the mdtext-param.**\
    ### This is a markdown heading'''
    alertbar = true
[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"
[taxonomies]
    tag = "tags"
    topic = "topics"
[author]
    name = "Salim KAYABASI"
    email = "salim.kayabasi@gmail.com"
[params.plugins]
    # CSS Plugins
    [[params.plugins.css]]
    URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
    # JS Plugins
    [[params.plugins.js]]
    URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
    [[params.plugins.js]]
    URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"
[menu]
    [[menu.main]]
    name = "About"
    URL = "about"
    [[menu.main]]
    name = "Blog"
    URL = "blog"
