name: Deploy
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/cache@v2.1.5
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Check install Hugo
        run: hugo version

      - name: Install dependencies
        run: npm ci

      - name: Check for linting errors
        run: npm test

      - name: Delete temporary directories
        run: npm run clean

      - name: Build production website
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: endsWith(github.ref, '/main') || endsWith(github.ref, '/test')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: salimkayabasi.com
          full_commit_message: ${{ github.event.head_commit.message }}
          user_name: Salim KAYABASI
          user_email: salim.kayabasi@gmail.com
