name: Readme

on:
  schedule:
    - cron: 0 18 * * *
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://salimkayabasi.com/blog/index.xml
          readme-section: feed
